gem/oq-platform

openquakeplatform/openquakeplatform/icebox/models.py, openquakeplatform/openquakeplatform/icebox/utils.py, openquakeplatform/openquakeplatform/local_settings.py.template
Fixes:
- Missing basemaps / basemaps have wrong names
- Sometimes a geoserver error is triggered
- Error during parallel maps creation
- Wrong map bbox and zoom
Probably fixes (more work needed):
- Missing thumbnails for icebox maps
TODO:
- ~~Enable only one layer on the map by default~~
- More testing
=> Fix how icebox maps are generated

openquakeplatform/openquakeplatform/gemecdwebsite/location/location.py
This bug produced "Internal server error" for location with this particular type of sub-section.
=> ecd: wrong id passed to find an index, fixed.

openquakeplatform/openquakeplatform/isc_viewer/dev_data/isc_data.csv, openquakeplatform/openquakeplatform/isc_viewer/dev_data/isc_data_app.csv, openquakeplatform/openquakeplatform/isc_viewer/gs_data/featuretypes/isc_viewer_measure.xml, openquakeplatform/openquakeplatform/isc_viewer/management/commands/import_isccsv.py, openquakeplatform/openquakeplatform/isc_viewer/models.py, openquakeplatform/openquakeplatform/isc_viewer/sql/measure.sql
The original data contained a wrong column name.
=> Rename ISC field 'smajaz' to 'smajax' as in ISC-GEM v1.05

openquakeplatform/openquakeplatform/__init__.py, openquakeplatform/openquakeplatform/templates/includes/footer.html, openquakeplatform/openquakeplatform/utils.py
=> Add OpenQuake platform version from git hash in the footer

openquakeplatform/openquakeplatform/templates/base/resourcebase_info_panel.html
- Removes the "More info" dropdown
- Removes text truncation on Abstract, Purpos and Supp. Information
=> Small improvements to the resourcebase page

openquakeplatform/openquakeplatform/utils.py, openquakeplatform/setup.py
Make version number more consistent. Avoid dupplication between setup.py and __init__.py
=> Make version number more consistent

openquakeplatform/openquakeplatform/utils.py, openquakeplatform/setup.py
=> Align the django-geoexplorer version with production

openquakeplatform/openquakeplatform/templates/includes/footer.html
Then in the future we can replace the link with a dedicated form
=> Add "Contact us" in the footer

openquakeplatform/openquakeplatform/templates/documents/document_detail.html
=> Add a "Download" button in documents view

openquakeplatform/openquakeplatform/gemecdwebsite/eventoverview/templates/eventoverview.html
I search whole code to find the same error pattern without succes. Seems appears just here.
=> back-compatibility with Leaflet stable version

openquakeplatform/openquakeplatform/vulnerability/static/vulnerability/js/capacity_curves.js
resolve a few missing variables needed for the x-axis d3 chart labels
=> Vuln bug fix

openquakeplatform/openquakeplatform/vulnerability/static/vulnerability/js/vulnerability_curves.js
This PR introduces a fix for vulnerability x axis overlapping chart labels
=> Vuln fix misc 6

openquakeplatform/openquakeplatform/templates/includes/footer.html
=> Add feedback link in footer

openquakeplatform/openquakeplatform/svir/views.py
See https://bugs.launchpad.net/oq-svir/+bug/1414711 and the QGIS-side companion https://github.com/gem/oq-svir-qgis/pull/9
=> SVIR: accept POST requests to export socioeconomic data

openquakeplatform/openquakeplatform/gemecdwebsite/eventdetails/templates/eventdetails.html, openquakeplatform/openquakeplatform/gemecdwebsite/eventoverview/eventoverview.py, openquakeplatform/openquakeplatform/gemecdwebsite/eventoverview/templates/eventoverview.html, openquakeplatform/openquakeplatform/gemecdwebsite/eventsmap/templates/eventsmap.html, openquakeplatform/openquakeplatform/gemecdwebsite/location/templates/location.html, openquakeplatform/openquakeplatform/gemecdwebsite/photo/templates/photopage.html, openquakeplatform/openquakeplatform/gemecdwebsite/static/gemecdwebsite/gemecd.css, openquakeplatform/openquakeplatform/gemecdwebsite/templates/gemecd_base.html
Add active resize of list of events and list of locations and place "back" links in ecd toolbar only.
=> Ecd fix scrollable

openquakeplatform/openquakeplatform/local_settings.py.template
=> Disable I18N since half of the website is not translated

openquakeplatform/openquakeplatform/icebox/models.py, openquakeplatform/openquakeplatform/icebox/templates/icebox.html
Also improve a bit the jobs list template.
=> Generate Icebox maps only when there are supported geo outputs

openquakeplatform/openquakeplatform/templates/calculate.html, openquakeplatform/openquakeplatform/templates/share.html
Simple updates to text on Share and Calculate pages.
=> Ph template updates

openquakeplatform/openquakeplatform/utils.py
=> Add the SITEURL var to the template context

openquakeplatform/pavement.py
list process of current-user only to check if all target process instances are shutted down.
=> fix per-user development stop target

openquakeplatform/openquakeplatform/static/js/irv_viewer_d3_tree.js
This PR improves the IRV-app d3.js tree in two ways:
* Include the operator info in the d3 tree chart
* Provide visual clue to the weights state
=> Irv update tree

openquakeplatform/openquakeplatform/static/js/irv_viewer.js
This PR resolves a small issue found in the IRV application. When the user makes a indicator selection for the map, then changes a weight, the selection is set back to 'IRI'.
=> Irv refactor

openquakeplatform/openquakeplatform/templates/documents/document_detail.html, openquakeplatform/openquakeplatform/templates/layers/layer_detail.html, openquakeplatform/openquakeplatform/templates/maps/map_detail.html
This PR includes the layer and map detail Django templates into the openquakeplatform application. In addition it provides a conditional if statement that will include '(user contributed)' into the title of any document, layer or map that has been an owner other then 'GEM'
=> User contributed banner

openquakeplatform/openquakeplatform/static/js/irv_viewer_PCP_theme.js
This PR includes a median line to the PCP theme chart
=> Add a median line to the IRV viewer theme chart

openquakeplatform/openquakeplatform/static/js/irv_viewer.js, openquakeplatform/openquakeplatform/static/js/irv_viewer_PCP_IRI.js, openquakeplatform/openquakeplatform/static/js/irv_viewer_PCP_primary.js, openquakeplatform/openquakeplatform/templates/irv_viewer.html
This PR includes a new primary indicator d3 chart for the IRV viewer application. 
Per the requirements, the application inspects the project definition and finds all the SVIR themes that have children. It then makes those themes who have children available in a dropdown selection menu. When the user selects a theme, the application automatically generates a d3 pcp chart of the selected theme's children. 
To test, load a project into the application.
Select the appropriate region field per the dialog.
Once the project is loaded into the application, select the 'primary chart' tab
Next select a theme from the selection dropdown menu that is inside the primary chart area.
=> Irv primary chart

openquakeplatform/openquakeplatform/templates/account/terms.html
Added sharing guidelines.  
Trivial updates to align license name with creative commons website
=> Ph update terms

openquakeplatform/openquakeplatform/static/css/oqplatform.css
=> Very small css fix to correctly center system-wide announcements

openquakeplatform/openquakeplatform/static/js/hrde.js, openquakeplatform/openquakeplatform/static/js/hrde_input_hazard_chart.js
This PR updates the HRDV input model MFD plots from line charts to histograms. 
To test, open any 'input model' in the HRDE app by clicking on "load hazard data'.
Next select a hazard model from the top selection dropdown menu.
Next select an input model and click 'add layer'.
* Note that the bar width is based on the number of features in the plot.
The plot should look something like this:
Rather then the old plot that was like this:
=> Mfd histograms

openquakeplatform/bin/migrate.sh, openquakeplatform/migrations/003_add_icmp_unaccent_operator.sql, openquakeplatform/openquakeplatform/models.py, openquakeplatform/openquakeplatform/vulnerability/models.py, openquakeplatform/openquakeplatform/vulnerability/views.py
Addresses https://bugs.launchpad.net/oq-platform/+bug/1459231
=> Add the unaccent custom type (both case insensitive and accent insensitive)

openquakeplatform/openquakeplatform/static/js/grv_viewer.js, openquakeplatform/openquakeplatform/templates/data_viewer_base.html, openquakeplatform/openquakeplatform/templates/hrde.html
This PR fixes a small error in the for loop that processed the UtfGrid metadata information. With the fix in place the application should now load and respond to each GRV theme. To test you can compere the app's behavior with the behavior of a platform that does not have the fix.
=> Fix the UtfGrid tile getJSON for loop

openquakeplatform/openquakeplatform/static/css/irv_viewer.css, openquakeplatform/openquakeplatform/static/js/irv_viewer.js, openquakeplatform/openquakeplatform/static/js/irv_viewer_PCP_primary.js, openquakeplatform/openquakeplatform/static/js/irv_viewer_PCP_theme.js, openquakeplatform/openquakeplatform/static/js/irv_viewer_d3_tree.js, openquakeplatform/openquakeplatform/templates/irv_viewer.html
This PR provides a number of improvements to UI and UX for the IRV viewer application.
1. Please note that now the d3 charts are no longer inside of a div that occupies the lower half of the screen. Now the map is full screen and the d3 chart div with tabs is in a floating dialog. This dialog can be moved and resized (with a minimum hight and width so not to interfere with the tabs). This allows the user to view both the map and the charts together even if the map is very portrait or landscape shaped. 
2. The majority of the time spent on this bug was to customize the SVG viewBox resizing to allow the d3.js project definition tree to resize dynamically with the containing div. Details aside, you can test this feature by loading a project into the app and once it has completely loaded you …
=> Irv ui ux improvements

openquakeplatform/openquakeplatform/taxtweb/bin/objectify.sh, openquakeplatform/openquakeplatform/taxtweb/mat_and_llrs.py, openquakeplatform/openquakeplatform/vulnerability/forms.py, openquakeplatform/openquakeplatform/vulnerability/templates/vulnerability/list.html, openquakeplatform/openquakeplatform/vulnerability/views.py
add filters for materials and LLRS
how to test:
add a curve with a specific Taxonomy (use taxtweb pop-up to populate it) and then try new filters on it.
Tests passed: https://ci.openquake.org/job/zdevel_oq-platform/73
=> Vuln taxtfilter

openquakeplatform/openquakeplatform/exposure/util.py
This should fix (or at least mitigate) https://bugs.launchpad.net/oq-platform/+bug/1472139
=> exposure/util.py: close forcefully cursor connection

openquakeplatform/openquakeplatform/static/js/irv_viewer.js
This PR resolves two very small typos in the IRV app
=> IRV viewer small typo

openquakeplatform/openquakeplatform/vulnerability/admin.py, openquakeplatform/openquakeplatform/vulnerability/forms.py, openquakeplatform/openquakeplatform/vulnerability/models.py, openquakeplatform/openquakeplatform/vulnerability/widgets.py, openquakeplatform/setup.py
Iteration to receive open issues on specs v.4 explanation document.
=> Vuln fix misc 7

openquakeplatform/openquakeplatform/static/js/irv_viewer.js
When testing and styling the tree with a project that has incomputable themes in the IRV web app for PR #442, I found some bugs in the app relating to the case when the SVI theme is not computable. This PR resolves those bugs that are explained in each commit.
=> Irv bugs found when SVI theme is not computable

openquakeplatform/bin/deploy.sh
Same as https://github.com/gem/oq-platform/pull/450 but for the production `deploy.sh` script.
=> deploy.sh: fix the sequence of importing GS layers

openquakeplatform/openquakeplatform/vulnerability/admin.py, openquakeplatform/openquakeplatform/vulnerability/forms.py, openquakeplatform/openquakeplatform/vulnerability/models.py, openquakeplatform/openquakeplatform/vulnerability/urls.py, openquakeplatform/openquakeplatform/vulnerability/views.py
I did not remove some unused variables, because I suppose they might become useful in the future, but I've added comments in those cases. There are also some long lines that would become a little harder to read if they are split into separate lines, so I kept them as they are.
=> Fix the majority of pep8 issues in the Vulnerability app

openquakeplatform/openquakeplatform/taxtweb/static/taxtweb/js/taxtweb.js, openquakeplatform/openquakeplatform/vulnerability/forms.py, openquakeplatform/openquakeplatform/vulnerability/models.py, openquakeplatform/openquakeplatform/vulnerability/widgets.py
To be able to set 'any taxonomy' as explicit choice.
=> vulnerability: add MultiValueField as taxonomy_text field

openquakeplatform/openquakeplatform/vulnerability/static/vulnerability/js/fragility_curves.js, openquakeplatform/openquakeplatform/vulnerability/static/vulnerability/js/vulnerability_curves.js, openquakeplatform/openquakeplatform/vulnerability/views.py
We found the json export problem and fix it, now we miss the UI management of it.
=> WIP: vuln: missing evaluation_of_im field added to empirical curves added

openquakeplatform/openquakeplatform/static/js/irv_viewer.js
The JSON element to access the application version number changed from svir_plugin_version to irmt_plugin_version.
=> Allow the application to use the new JSON naming convention

openquakeplatform/bin/deploy.sh
This fixes #470. Installation tests are green: https://ci.openquake.org/job/zdevel_oq-platform/110/
Upgrade tests are done manually (and it worked).
=> deploy.sh: do not load initial data during upgrades

openquakeplatform/openquakeplatform/templates/calculate.html
- Update RMTK link
- Replace old oq-engine manual
=> Update the 'calculate' static page

openquakeplatform/openquakeplatform/static/css/risk_input_model.css, openquakeplatform/openquakeplatform/static/js/risk_input_model_fragility.js, openquakeplatform/openquakeplatform/static/js/risk_input_model_vulnerability.js, openquakeplatform/openquakeplatform/templates/risk_input_preparation_toolkit.html
This PR changes the fragility loss category menu from a test input to a selection menu.
Plus a few other typos
=> Change the loss category input to a selection menu

CHANGELOG, openquakeplatform/openquakeplatform/vulnerability/models.py, openquakeplatform/openquakeplatform/vulnerability/views.py
=> Vuln hotfix01

openquakeplatform/openquakeplatform/local_settings.py.template
Some useful formats were missing
=> settings: and more document formats

CHANGELOG, openquakeplatform/openquakeplatform/taxtweb/static/taxtweb/js/taxtweb.js
fix elements of group of material technologies ('mat_tech_grp') are wrongly assigned (fixes #500)
=> fix elements of group of material technologies

openquakeplatform/openquakeplatform/vulnerability/static/vulnerability/css/vulnerability.css, openquakeplatform/openquakeplatform/vulnerability/templates/vulnerability/show_general_information.html, openquakeplatform/openquakeplatform/vulnerability/views.py
Add disclaimer and email contact to ask questions at the bottom of physical vulnerability curves view page .
=> Vulnerability disclamer and email.

openquakeplatform/openquakeplatform/exposure/static/exposure/exposure_controller.js, openquakeplatform/openquakeplatform/exposure/templates/exposure/export.html, openquakeplatform/openquakeplatform/exposure/views.py, openquakeplatform/openquakeplatform/local_settings.py.template, openquakeplatform/openquakeplatform/utils.py
This should fix #518 
Test are running on CI: https://ci.openquake.org/job/zdevel_oq-platform/184/
=> Exposure: move the limits in local_settings.py

openquakeplatform/openquakeplatform/static/js/supplemental_layer_options.js
In case the selected layer has already been added to the map, then we just bring such layer to front.
This PR partially addresses https://github.com/gem/oq-platform/issues/525
=> HRDE - Avoid re-adding existing supplemental layers

openquakeplatform/openquakeplatform/grv/static/grv/grv_viewer.js
This PR allows keeping the same color for a line dedicated to a country in the PCP chart.
this is my first platform PR so be nice ;)
=> mantain line color for a nation when adding more

openquakeplatform/openquakeplatform/test/oqplatform.py
Tests are green: https://ci.openquake.org/job/zdevel_oq-platform/195/
=> Do cleanup in fini; some additional comments

openquakeplatform/openquakeplatform/test/ript_test.py
We forgot to add it to git before opening the previous PR.
Tests are green: https://ci.openquake.org/job/zdevel_oq-platform/200/
=> RIPT: add the first selenium test

CHANGELOG, openquakeplatform/openquakeplatform/test/vulnerability_test.py, verifier.sh
Add management of firefox updates to avoid selenium malfunctions during tests
=> Firefox updates management

CHANGELOG, openquakeplatform/openquakeplatform/irv/static/irv/js/irv_viewer.js
=> IRV - when switching project definition, restyle the map accordingly

openquakeplatform/openquakeplatform/templates/calculate.html
So we do not need to redeploy each time...
=> Make the link to the OQ manual more generic

CHANGELOG, openquakeplatform/openquakeplatform/irv/static/irv/js/irv_viewer.js
Fixes https://github.com/gem/oq-platform/issues/560
=> IRV - In the mapInfo box, show only irmt-related information

openquakeplatform/bin/deploy.sh, verifier.sh
Renamed parameter 'host' with 'hostname'  because hided by fab machinery
=> Fab host fix

openquakeplatform/migrations/009_remove_mapquest.sql, openquakeplatform/openquakeplatform/exposure/static/exposure/exposure_export.js, openquakeplatform/openquakeplatform/gemecdwebsite/eventdetails/templates/eventdetails.html, openquakeplatform/openquakeplatform/gemecdwebsite/home/templates/home.html, openquakeplatform/openquakeplatform/gemecdwebsite/location/templates/location.html, openquakeplatform/openquakeplatform/gemecdwebsite/templates/gemecd_base.html, openquakeplatform/openquakeplatform/grv/static/grv/grv_viewer.js, openquakeplatform/openquakeplatform/hazus/static/hazus/hazus.js, openquakeplatform/openquakeplatform/hrde/static/hrde/hrde.js, openquakeplatform/openquakeplatform/irv/static/irv/js/irv_viewer.js, openquakeplatform/openquakeplatform/local_settings.py.template, openquakeplatform/openquakeplatform/static/js/base_map_options.js, openquakeplatform/openquakeplatform/templates/base_map_options.html
See #600 
Tests: https://ci.openquake.org/job/zdevel_oq-platform/305/
This is a temporary fix: we should at least
- Add google (key required)
- ~~Add a new providers (like MapBox having a working key)~~ (supported only in GeoNode master, see http://lists.osgeo.org/pipermail/geonode-devel/2016-July/001075.html)
=> Remove MapQuest layers

openquakeplatform/openquakeplatform/local_settings.py.template
=> More settings cleanup

openquakeplatform/openquakeplatform/vulnerability/templates/admin/vulnerability/base_site.html, verifier.sh
A new parametric variable for 'taxtweb' must be created in 'vulnerability' too, because it use taxtweb JS API.
Tests are green here: https://ci.openquake.org/job/zdevel_oq-platform/414/
=> Fix tax base

verifier.sh
Installation Firefox 53 on Pla with Ubuntu 12.04
=> Installation Firefox 53 on Ubuntu 12.04

openquakeplatform/openquakeplatform/templates/calculate.html
Delete info and link for oq-hazardlib, rmtk and nrml converter in calculate.html
Tests green here: https://ci.openquake.org/job/zdevel_oq-platform/429/
=> Delete info and link for oq-hazardlib,rmtk and nrml converter

openquakeplatform/openquakeplatform/python3compat.py
Required by https://github.com/gem/oq-platform-ipt/pull/35
=> Add python3compat.py
