gem/oq-platform

- openquakeplatform/openquakeplatform/local_settings.py.template
Revert changes made in #217 because this configuration gives an 404 when a non superuser tries to add a layer to a map:
We need to take this revert into account when we change protocol and or hostname. A change in the platform urls will break all the maps. Probably it would be better to solve the issue in other ways.
> Revert GEOSERVER_URL to absolute URL, relative gives a 404 in GXP

- openquakeplatform/openquakeplatform/local_settings.py.template
- openquakeplatform/openquakeplatform/templates/site_base.html
- openquakeplatform/openquakeplatform/utils.py
Code is enabled only when a `UA-*****` is provided through the `local_settings.py`.
The `GOOGLE_UA` in settings is not mandatory.
> Add support for Google Analytics using local_settings.py

- openquakeplatform/openquakeplatform/exposure/static/exposure/exposure-export.css
This PR resolves a small css conflict between the labels and the leaflet layer control labels.
> override the leaflet contorl layer labels override

- openquakeplatform/openquakeplatform/vulnerability/static/vulnerability/js/vulnerability_curves.js
In the case that a discrete Vulnerability function has y-axis labels less than 0.2 we need to modify the data formatter.
> Modify the data formatter

- openquakeplatform/openquakeplatform/svir/urls.py
- openquakeplatform/openquakeplatform/svir/views.py
This addresses https://bugs.launchpad.net/oq-platform/+bug/1411611 and is related to https://bugs.launchpad.net/oq-svir/+bug/1411613
* Add API method to list countries and iso codes (useful to populate in QGIS a list of countries for which socioeconomic data are available)
* when exporting socioeconomic data, accept an additional optional parameter to refine the filtering by iso codes (I renamed a API method, but the old name is still available for compatibility with the old client versions, and the old workflow still works)
> When exporting socioeconomic data, enable to filter by a list of country iso codes

- openquakeplatform/openquakeplatform/svir/urls.py
- openquakeplatform/openquakeplatform/svir/views.py
Needed by https://github.com/gem/oq-svir-qgis/pull/11
(see also https://bugs.launchpad.net/oq-svir/+bug/1411598)
> SVIR: add API to get the url needed to download a layer's TC211 metadata

- openquakeplatform/openquakeplatform/local_settings.py.template
This allows the reverse proxy to load TaxTweb as a standalone application
> Add TaxTweb to AUTH_EXEMPT_URLS

- openquakeplatform/openquakeplatform/icebox/models.py
This PR will trigger layer and maps removal when an Icebox calculation is deleted. It will also DROP the database view associated with the icebox output.
We are missing a migration to add layers previously produced by Icebox in the "icebox" layers group. This will be part of a separate PR.
Thanks @ptormene for the peering.
> Icebox layer deletion

- openquakeplatform/openquakeplatform/__init__.py
- openquakeplatform/openquakeplatform/utils.py
- openquakeplatform/openquakeplatform/version.py
When the code is installed in a clean environment, without Django,
utils.py cannot be imported but is required to get code version.
> Move git_suffix out of utils.py since utils requires Django.

- openquakeplatform/bin/deploy.sh
Fix migrations copy in deploy.sh where some file extensions are not present in the src folder.
`cp` fails if any of `*.sh`, `*.sql` or `*.py` is not present in the migrations dir. This will bring `deploy.sh` to a failure.
> Fix migrations copy in deploy.sh

- openquakeplatform/openquakeplatform/static/js/hazus.js
- openquakeplatform/openquakeplatform/static/js/hrde.js
This PR provides logic to hide the leaflet layer controller when no layers are loaded, and then show the controller when layers are present. The feature is only required in the Hazus and HRDE applications as all other leaflet based applications are preloaded with layers.
> Layers selector

- openquakeplatform/openquakeplatform/icebox/static/icebox/calculate.js
- openquakeplatform/openquakeplatform/icebox/templates/icebox.html
This solves the issue where the same traceback is reported to all the failing jobs, causing confusion on the causes of a failure.
This also replace pop-ups with a modal dialog. Pop-ups are evil: sometime they are blocked, they go back the main windows... and so; since our pop-ups are "self called" (they are not pointing to an external url) are also difficult to style and manage. Now syntax highlighting can be easily added.
Fixes: https://bugs.launchpad.net/oq-platform/+bug/1434177
More testing is needed before releasing the [WIP].
> Improve traceback display. Use bootstrap modal instead of popups

- openquakeplatform/bin/deploy.sh
- openquakeplatform/fabfile.py
GeoNode already provides an helper to do that. This PR removes redundant code.
See: https://github.com/gem/geonode/blob/2.0.x/geonode/base/management/commands/fixsitename.py
> Simplify django site configuration

- openquakeplatform/openquakeplatform/svir/urls.py
- openquakeplatform/openquakeplatform/svir/views.py
Given a layer identifier and a project definition, if the logged user is enabled to modify the layer, the project definition will be added to the layer's supplemental information. In order to ensure backward compatibility, the supplemental information can contain a single json object. In that case, it will be converted into an array, and both the existing project definition and the new one will be sequentially appended.
> SVIR: new API to append a project definition to an existing layer

- openquakeplatform/openquakeplatform/svir/views.py
This looks too lucky to be true, but Ben confirmed it works. I found out that `layer` has the attribute `supplemental_information`, so we don't need to retrieve that through the `base_resourcebase` table. I did not expect it to be accessible directly from `layer`, so in the previous implementation I looked for that inside the metadata stuff.
After saving `layer`, everything is automatically synchronized, so the new project definition is promptly available, without needing to trigger any further updating procedure.
> SVIR - Fix the API to add a new project definition to one of the available layers

- openquakeplatform/openquakeplatform/svir/views.py
Before this PR, the exported csv was first built, then returned. Now I use a generator to stream the data. This will be helpful to improve the QGIS plugin's downloader, which will be able to start streaming the data without the initial waiting.
No companion PR at QGIS side is required (these changes do not break the current downloader)
> SVIR - Stream socioeconomic data

- openquakeplatform/openquakeplatform/svir/views.py
Also avoid adding the project definition if the title is undefined or blank
> Forbid adding a new project definition if it has the same title of an old one

- openquakeplatform/migrations/002_remove_bluemarble.sql
- openquakeplatform/openquakeplatform/common/post_fixtures/maps.json
Bluemarble has been already deprecated as baselayer for new maps, but it's still present in fixtures and pre-generated maps (and their child).
This PR updates pre-generated maps fixures and add an SQL migration to remove the layers from any maps already stored.
> Remove the bluemarble baselayer from previously created maps

- openquakeplatform/openquakeplatform/static/js/irv_viewer.js
- openquakeplatform/openquakeplatform/static/js/irv_viewer_PCP_primary.js
- openquakeplatform/openquakeplatform/static/js/irv_viewer_PCP_theme.js
- openquakeplatform/openquakeplatform/static/js/irv_viewer_d3_tree.js
- openquakeplatform/openquakeplatform/templates/irv_viewer.html
This PR includes several small UX improvements. 
1. Automatically select and trigger the selection of the first project definition in the selection dropdown menu. To test, open the IRV application, and select a project. The loading spinner will indicate that the APIs are working, after a few moments, the loading spinner will be hidden and now you can see that the first project definition has been automatically selected in the dropdown menu and triggered. In addition, this d3.js project definition tree is now rendered.
2. Automatically select and trigger the selection of the first primary indicator. Similar to #1, once a project has been selected, the first primary indicator from inside the 'primary indicator chart' tab is automatically selected and triggered.
3. Disable the theme tab if …
> Irv small ux improvements

- openquakeplatform/openquakeplatform/taxtweb/static/taxtweb/js/taxtweb.js
- openquakeplatform/openquakeplatform/taxtweb/static/taxtweb/js/taxtweb_maps.js
- openquakeplatform/openquakeplatform/taxtweb/taxonomy_map.py
- openquakeplatform/openquakeplatform/taxtweb/templates/taxtweb/index.html
All numerical fields (are all in "Building Information" tab) now are verified in 2 different way:
- interactively if you compile the form
- not interactively if you are opening a taxtonomy passing it by part of a URL
**HOW TO TEST IT**
- open taxtweb and play with "Building Information" tab
- click on "Permalink" when no field is broken and try to manipulate the resulting new URL
- placing strings instead of numbers, negative number, float instead of integer and so on.
> Taxt short2

- openquakeplatform/openquakeplatform/static/js/irv_viewer.js
- openquakeplatform/openquakeplatform/static/js/irv_viewer_PCP_primary.js
- openquakeplatform/openquakeplatform/templates/irv_viewer.html
This PR includes provides the IRV web application with logic to check that the composite indicators (previously known as the primary indicators) are scaled, and if they are not, provide the user with a warning message and a button that will scale them.
To test this PR, simply load a project that does not have scaled primary indicators, for example the project called 'testing iri small UX improvements'. 
Once the project has loaded, select the primary indicator tab and you should see the warning message like this:
After clicking on the button to scale the composite indicators, the composite indicators are scaled, and all the charts are re-rendered.
This PR also renames the primary indicators to composite indicators, per the project owners request.
> Irv scale composite indicators

- openquakeplatform/openquakeplatform/static/js/irv_viewer.js
Per the request of the project owner, the charts will no longer be rendered when the composite data is incomplete. We now check for incomplete data, provide a warning message to the user and then stop the function from rendering the charts.
To test this PR, load a project that has incomplete data, you will then seem in each of the chart tabs a warning message like the this: 
Please note that the tree chart is still visible and the user can still modify weights and save new versions of the project definition. The thematic map is not rendered to the map as the values are also dependent on the composite data.
> Irv manage incomplete data2

- openquakeplatform/openquakeplatform/static/js/irv_viewer.js
With the thematic in global scope, the application is able to remove any previously rendered map on each iteration of the block of code. This will prevent the maps overlapping eachother.
You can test this by modifying the web application so that it will render a new map (change weights, inversions, or make a new selection from the map indicator pull down menu. 
You will see that the map layers are not overlapping because the opacity of the map will remain constant (if the maps overlap, then the opacity will appear to change).
> Place the thematic map variable into the global scope

- openquakeplatform/openquakeplatform/templates/base/resourcebase_info_panel.html
Update the GeoNode layers template in order to not show supplemental information when the category is SVIR
I needed to use stringformat in the filter because the category variable in surrounded by whitespace and a simple filter would not work.
To test, in the OQP open a layer the contains the category 'SVIR', you should NOT see the supplemental information metadata field. Then selected another layer that has category 'Hazard' (for example), and you should see the supplemental information metadata field
> Update the GeoNode layers template

- openquakeplatform/openquakeplatform/static/js/irv_viewer.js
Check the svir plugin version, warn the user and stop the application if the version is older than 1.4.3
To test this feature, load a project that has a svir_plugin_version < 1.4.3. 
The application will render a warning message like this:
If a project is loaded into the application with a version => 1.4.3, then the project will be loaded as normal.
> Check the svir plugin version

- openquakeplatform/openquakeplatform/exposure/static/exposure/exposure_controller.js
- openquakeplatform/openquakeplatform/exposure/templates/exposure/export.html
Fix for launchpad bug 1469636 
https://bugs.launchpad.net/oq-platform/+bug/1469636
The key issue is that the study_id is passed to export API calls instead of the study_region_id.
This bug was not immediately obvious for two reasons:
*  for many studies (PAGER, most UN Habitat Level 0), study_id==study_region_id
*  the handling for sub-national studies is slightly different
As described in the launchpad bug, all NERA national studies are affected, as as the UN Habitat L0 studies for Mexico, Mongolia, South Africa and Ukraine. 
This pull request replaces study_id with the study_region_id from the selected study region.
In order to confirm that the coordinates are correct, I recommend loading the CSV data into QGIS over an OpenLayers background so as to check that the downloaded area …
> Exposure export bug 1469636

- openquakeplatform/openquakeplatform/static/js/irv_viewer.js
- openquakeplatform/openquakeplatform/static/js/irv_viewer_d3_tree.js
This small PR include some styling improvements to the d3js tree chart in the IRV web application. This PR can be tested by loading a project that includes some nodes who's values are not computable into the IRV web app.
Before, the tree chart rendered the nodes and node branches regardless of weather or not the source node values are computable:
After, If the source node values are not computable, then the node and its branch are rendered with some opacity:
> Irv update tree

- openquakeplatform/setup.py
This should make Jenkins happy. Currently is broken with the following error:
```
Downloading/unpacking django-chained-selectbox==0.2 (from openquakeplatform==1.2.0-git94300dd)
Could not find a version that satisfies the requirement django-chained-selectbox==0.2 (from openquakeplatform==1.2.0-git94300dd) (from versions: )
No distributions matching the version for django-chained-selectbox==0.2 (from openquakeplatform==1.2.0-git94300dd)
```
Regression of https://github.com/gem/oq-platform/commit/cb54d19b9c428a0fe134186059cdabf45eaf9b5e
> setup.py: update django-chained-selectbox to 0.2.1

- openquakeplatform/openquakeplatform/static/css/irv_viewer.css
- openquakeplatform/openquakeplatform/static/js/irv_viewer.js
- openquakeplatform/openquakeplatform/static/js/irv_viewer_d3_tree.js
- openquakeplatform/openquakeplatform/templates/irv_viewer.html
This PR provides a number of small UI/UX improvements to the IRV d3js tree chart.
Summary of fixes:
The project definition dialog loading spinner is now hidden only after the tree chart in rendered. This needed when the composite indicator data is incomplete. 
Resolved the labeling conflict between IR and SVI (when SVI has many children)
Resolved labeling issue when attribute label are more then 20 characters. In the case that attribute labels are more then 20 characters, I am substituting the attribute name with an acronym. This acronym can be hovered with the mouse, in which case the full attribute name is rendered on the top left of the dialog. Also note that all labels that can be hovered are rendered in blue, which gives the user a visual clue that it can be interacted with.
Result:
> Irv conflicting labels

- openquakeplatform/fabfile.py
This fixes an issue about keywords and metadata.
With the previous behavior GS was synchronizing with an empty GN: this was causing all the keywords to disappear in GS.
Now the sequence is:
- Load the fixture in the GN database
- Push the GS data
- Synchronize GS data with GN
Unblock https://github.com/gem/oq-platform/pull/449
Tests https://ci.openquake.org/job/zdevel_oq-platform/76/
> fabfile.py: fix the sequence of importing GS layers

- verifier.sh
Added product installation test (it needs minor changes to production CI job when merged).
Now you can test production installation too, accordingly with CI checkbox button.
Test passed: https://ci.openquake.org/job/zdevel_oq-platform/94/
> Testing: production installation test added to CI job

- openquakeplatform/openquakeplatform/static/js/irv_viewer.js
Companion of https://github.com/gem/oq-svir-qgis/pull/91
For now, we are keeping the platform-side svir app as it is, but in the future we might want to rename it into irmt, for instance as soon as we will substitute the old DB with the new one holding subnational data.
> IRV_VIEWER: check vs irmt_plugin_version instead of svir_plugin_version

- openquakeplatform/openquakeplatform/templates/hrde.html
- openquakeplatform/openquakeplatform/templates/irv_viewer.html
In the web applications that are using AngularJs for dynamic and responsive selection menus (IRV & HRDE), there is an annoying bug where each menu has an empty option as the first child of selection element. 
This PR includes a fix for this bug as found on the second highest rated answer here: http://stackoverflow.com/questions/12654631/why-does-angularjs-include-an-empty-option-in-select
With this solution the menu now does not include an empty first child element:
> Angular empty selection bug

- openquakeplatform/openquakeplatform/static/jasmine/spec/SpecIRV.js
- openquakeplatform/openquakeplatform/static/js/irv_viewer.js
The QGIS toolkit has been updated to provide a layer tag "irmt_plugin_version" as apposed to the older "svir_plugin_version". This PR updates the IRV Jasmine unit tests to support both options.
> Update the IRV unit tests per the recent QGIS toolkit refactor

- openquakeplatform/openquakeplatform/static/js/irv_viewer.js
This update will:
1) check for a match between the major release numbers
2) check for match between the minor release numbers
3) not check for patch numbers
This means that any version number with 1.7.X will be compatible with
the IRV app.
Closes #479
> Refactor the version comparison function

- openquakeplatform/openquakeplatform/exposure/util.py
- openquakeplatform/openquakeplatform/exposure/views.py
Please note that this changes the output of the API. In particular, `num_l1_studies` is not returned anymore. Instead, `num_studies`, `num_l1_names` and `num_l2_names` are returned (please see the new docstring for further details)
> Exposure: add num_l2_studies to the output of get_all_studies API

- openquakeplatform/fabfile.py
This fix avoids failures when an isolated venv is used since the latest version of mock is not compatible with the Ubuntu 12.04 setuptools version
```
Downloading/unpacking mock
Downloading mock-1.3.0.tar.gz (70Kb): 70Kb downloaded
Running setup.py egg_info for package mock
mock requires setuptools>=17.1. Aborting installation
Complete output from command python setup.py egg_info:
mock requires setuptools>=17.1. Aborting installation
```
> fabfile.py: make PYTHON_TEST_LIBS versions explicit

- openquakeplatform/openquakeplatform/static/js/risk_input_model_fragility.js
- openquakeplatform/openquakeplatform/templates/risk_input_preparation_toolkit.html
This Pr fixes 2 small bugs in the Risk input preparation toolkit.
The first bug is that fragility functions did not include the loss category.
The second bug is that there was extra white space in front of the limit states tag for fragility / continuous functions.
> Risk ipt missing loss category

- openquakeplatform/openquakeplatform/local_settings.py.template
- openquakeplatform/openquakeplatform/templates/risk_input_preparation_toolkit.html
This PR adds the Risk Input Preparation Toolkit to the `AUTH_EXEMPT`, thus removing the authentication from it.
This tool does not provide any data (it's just a "converter") and this will reduce the overhead and the noise related to the authentication during the risk workshop.
> Add the RIPT to the AUTH_EXEMPT

- openquakeplatform/openquakeplatform/svir/views.py
Recently, to avoid potential inconsistencies, we changed the `theme` attribute of `Indicator` into a property, so the `Indicator` is directly linked to a `subtheme` and the `subtheme` belongs to one of the `themes`. But we forgot to change one filter, so the API was unable to retrieve indicators belonging to a given `theme` if no `subtheme` was specified. This PR fixes such case.
> svir: fix filtering indicators by theme

- CHANGELOG
- openquakeplatform/openquakeplatform/local_settings.py.template
- openquakeplatform/openquakeplatform/templates/calculate.html
- openquakeplatform/openquakeplatform/urls.py
Icebox isn't supported since OpenQuake Engine 1.6. Users can use OATS instead.
Test: https://ci.openquake.org/job/zdevel_oq-platform/185/
> Disable the icebox application

- openquakeplatform/openquakeplatform/test/oqplatform.py
...in order to avoid hiding an error message caused by missing config
> selenium: make screenshot only if Firefox driver is present

- openquakeplatform/openquakeplatform/test/failurecatcher.py
Tests are green: https://ci.openquake.org/job/zdevel_oq-platform/201
from: 
```
test_allowed_methods (openquakeplatform.exposure.tests.DecoratorUtilTestcase) ... ok
test_sign_in_required (openquakeplatform.exposure.tests.DecoratorUtilTestcase) ... ok
test_invalid (openquakeplatform.exposure.tests.ExportAreaValidTestCase) ... ok
...
```
to:
```
openquakeplatform.test.dumb_test.DumbTest.dumb_test ... ok
openquakeplatform.test.irv_test.IrvTest.irv_test ... ok
openquakeplatform.test.isc_test.IscTest.isc_test ... ok
...
```
output.
> nose: customization of result lines output

- openquakeplatform/openquakeplatform/irv/static/irv/js/irv_viewer.js
- openquakeplatform/openquakeplatform/irv/static/irv/js/irv_viewer_d3_tree.js
Addressing points 1 and 3 of #540, removing some unused code and fixing some minor details that caused warnings by my syntax checker.
The `addProjectDefinition` function was not used anywhere, and exactly the same code was already used elsewhere, so I kept only the other (used) block.
The main change made by this PR is to leverage the `svir/add_project_definition` API to check the uniqueness of the name assigned to the new project definition. The IRV app was doing the same check, which was redundant and has been therefore removed.
> IRV: use api check for unique name

- openquakeplatform/openquakeplatform/test/oqplatform.py
- openquakeplatform/openquakeplatform/test/vulnerability_test.py
- verifier.sh
Seems that a transient inconsistency in selenium is reflected in our tests broken them.
Added a delay between 2 critical operation is a good workaround.
Test are running here: https://ci.openquake.org/job/zzdevel_oq-platform/
and we scheduled a bunch of new jobs instances to be sure the problem is constantly solved.
> Tests timeouts fix

- CHANGELOG
- openquakeplatform/openquakeplatform/irv/static/irv/js/irv_viewer.js
- openquakeplatform/openquakeplatform/irv/static/irv/js/irv_viewer_d3_tree.js
Final steps to fix https://github.com/gem/oq-platform/issues/540
The issue was partially fixed by https://github.com/gem/oq-platform/pull/541. After cleaning the project definition in order to avoid a recursion issue, we also had to re-parse it before adding it to the list of available project definitions.
I've also solved an annoying issue that was due to the fact that the handler for the submission of a new project definition was re-defined and triggered every time the `loadPD` function was called, instead of defining it separately and calling it only when the `submitPD` button is triggered. Extracting that function, the events work in the right order and we don't need anymore those ugly workarounds (timeouts, etc) that only partially solved the effects of this misbehavior. One of the …
> IRV - Fix the selection of newly added project definitions

- CHANGELOG
- openquakeplatform/openquakeplatform/irv/static/irv/css/irv_legend.css
- openquakeplatform/openquakeplatform/irv/static/irv/js/irv_viewer.js
- openquakeplatform/openquakeplatform/irv/static/irv/js/irv_viewer_PCP_IRI.js
- openquakeplatform/openquakeplatform/irv/static/irv/js/irv_viewer_PCP_primary.js
- openquakeplatform/openquakeplatform/irv/static/irv/js/irv_viewer_PCP_theme.js
- openquakeplatform/openquakeplatform/irv/static/irv/js/irv_viewer_d3_tree.js
- openquakeplatform/openquakeplatform/irv/templates/irv/irv_viewer.html
While working in the direction described by the title, I made a couple of improvements/fixes:
* moving the mouse over the median line, now the text 'median' is correctly displayed for all charts (before, it produced errors in some cases)
* I've added the zooming/panning functionality to all the charts, also removing the scrollbars to those widgets and fixing the layouts in order to let the charts fill the whole available space 
Tests are green: https://ci.openquake.org/job/zdevel_oq-platform/233/
> IRV - Use separate widgets (instead of tabs), to display charts

- openquakeplatform/openquakeplatform/taxtweb/templates/taxtweb/incl_taxtweb_content.html
- openquakeplatform/openquakeplatform/taxtweb/templates/taxtweb/incl_taxtweb_inlinecss.html
A new button is added to open a new popup (or tab) to http://www.globalquakemodel.org/what/physical-integrated-risk/building-taxonomy/
Fix #556
> taxtweb: add introduction link to building taxonomy

- openquakeplatform/openquakeplatform/ript/static/ript/risk_input_model_exposure.js
When generating an exposure model using the aggregated value option, and extra “ is written in the output file. I used the attached exposure information (exposure_example.txt) which led to the exposure_example.xml also attached.
It fixes #561.
> ript: hotfix for Aggregated Structural Costs case syntax error.

- openquakeplatform/openquakeplatform/hrde/static/hrde/hrde.js
Otherwise clicking the button would cause to discard whatever you had already done in the hrde.
> HRDE: open terms of use in a new tab instead of the current one

- CHANGELOG
- openquakeplatform/openquakeplatform/irv/static/irv/js/irv_viewer.js
I believe color themes are not actually useful in this application, because:
1. We display one single layer at a time, so we don't need to differentiate styles of different layers
2. Below the layer, we always have OpenStreetMap (and the user can't change it), so we just need to use colors that look fine with it.
Furthermore, the theme management contained a bug, that caused the application to become slower and slower every time a different color theme was selected. Instead of attempting to fix the bug, I am rather proposing to remove the unused feature (resolves https://github.com/gem/oq-platform/issues/504)
> IRV - Remove color themes

- openquakeplatform/openquakeplatform/ript/views.py
From `validate_nrml` I extracted `validate_nrml` and `sendback_nrml`. I placed the common code into a third function `_do_validate_nrml`
> Divide the validate_nrml function into 2 separate functions

- openquakeplatform/fabfile.py
- openquakeplatform/openquakeplatform/local_settings.py.template
Fabric us host as reserved variable to specify the name of target host to try to perform installation instead of localhost, hiding the argument 'host' of target function.
> Renamed fab argument host to hostname because the first is reserved.

- openquakeplatform/openquakeplatform/irv/static/irv/js/irv_viewer.js
Partially addressing https://github.com/gem/oq-platform/issues/583
With this change, instead of just displaying the raw and unsorted data, the application searches the extended names and types of variables by scanning the project definition. Then the variables are presented in a structured way, collected by type.
Tests are green: https://ci.openquake.org/job/zdevel_oq-platform/252/
> IRV - When clicking on the map, show zonal information in a more structured way

- openquakeplatform/openquakeplatform/irv/static/irv/spec/SpecIRV.js
These additional tests check that the application keeps working as expected in case indicators contain any null values, as it should be after recent improvements.
In order to check it, I have duplicated some tests, slightly modifying the copies by replacing some values with some `null`.
Tests are green: https://ci.openquake.org/job/zdevel_oq-platform/299/
> IRV: add tests handling missing values

- openquakeplatform/openquakeplatform/templates/calculate.html
For the Engine 2.0
Now the links are pointing directly to the resources and they don't link to the website anymore (which is not well maintained).
I would suggest to improve more this page and remove pages for the website, making it just pointing here.
> Improve and update the calculate page

- CHANGELOG
- openquakeplatform/openquakeplatform/irv/static/irv/js/irv_viewer.js
- openquakeplatform/openquakeplatform/irv/static/irv/js/irv_viewer_d3_tree.js
- openquakeplatform/openquakeplatform/irv/templates/irv/irv_viewer.html
This PR enables the Integrated Risk Viewer (IRV) to visualize projects in which the Integrated Risk was obtained through a custom calculation. In this case, the IRI will not be recalculated, and its values will just be read from a field specified by the user. The project definition also contains a description of the customized calculation.
Please see the companion: https://github.com/gem/oq-irmt-qgis/pull/146
In my local machine tests are green.
> IRV - Custom operator

- CHANGELOG
- openquakeplatform/openquakeplatform/irv/static/irv/js/irv_viewer.js
- openquakeplatform/openquakeplatform/irv/static/irv/js/irv_viewer_d3_tree.js
- openquakeplatform/openquakeplatform/irv/static/irv/spec/SpecIRV.js
- openquakeplatform/openquakeplatform/irv/templates/irv/irv_viewer.html
For simplicity, I prefer to disable changing weights whenever any of the nodes in the current project uses a custom operator. Before, I was allowing to change weights in the single case in which the IRI node was using a custom operator, but not the others. I found a little bug in that solution, and anyway I prefer to keep things a little simpler.
There was also a case in which the map was not displayed, so I fixed it too.
> irv: disable changing weights in all projects using custom operators

- CHANGELOG
- openquakeplatform/openquakeplatform/irv/static/irv/js/irv_viewer.js
- openquakeplatform/openquakeplatform/irv/static/irv/js/irv_viewer_d3_tree.js
I am keeping backwards compatibility, so the old projects can still be visualized.
With the proposed changes, the IRV will be able to read also projects created by the IRMT QGIS plugin after the changes introduced in the following commit:
https://github.com/gem/oq-irmt-qgis/commit/03b8a3d15c31cdc7b852a7b3ad4aa0bdade8a6e0
While displaying the tree, the IRV will visualize also the custom formula or its textual description, if they are specified in the project definition.
Jasmine tests are green.
> IRV: enable reading projects using a modified custom operator format

- verifier.sh
Now oq-moon is accessible by other part of the test code.
A single test mysteriously fails once, than all green:
https://ci.openquake.org/job/zdevel_oq-platform/383/
> Engine fix moon

- docs/Development-environment-on-Ubuntu-12.04.md
- openquakeplatform/bin/deploy.sh
- openquakeplatform/fabfile.py
- verifier.sh
There were several issues:
- The installation of engine and hazardlib was trying to download and build dependencies from pip. The 12.04 stack isn't tested and supported in engine and hazardlib, then now we install them with `--no-deps`. This also applies to ipt which has hazardlib + engine in its dependencies.
- Some parts of the installation were still looking for `openquake.commonlib.nrml` instead of `openquake.hazardlib.nrml`
- `oq-moon` git clone had wrong syntax
https://ci.openquake.org/job/zdevel_oq-platform/376
Fixes #626
> FIx platform installation

- openquakeplatform/openquakeplatform/local_settings.py.template
- openquakeplatform/openquakeplatform/urls.py
- verifier.sh
With this PR we add the new "Building Classification Survey" platform plugin integration.
Tests are green: https://ci.openquake.org/job/zdevel_oq-platform/386/
> add building-class 

- openquakeplatform/bin/deploy.sh
- openquakeplatform/fabfile.py
- openquakeplatform/openquakeplatform/local_settings.py.template
- openquakeplatform/openquakeplatform/test/isc_test.py
- openquakeplatform/openquakeplatform/test/nose_runner.py
- verifier.sh
With this PR oq-platform is decoupled from the oq-engine code-base just interacting via http requests.
It is companion of oq-platform-ipt PR https://github.com/gem/oq-platform-ipt/pull/29.
Tests are green here: https://ci.openquake.org/job/zdevel_oq-platform/410/
> Moving from oq-engine as library to oq-engine as web-service

- openquakeplatform/openquakeplatform/local_settings.py.template
- openquakeplatform/openquakeplatform/templates/includes/header.html
- openquakeplatform/openquakeplatform/templates/share.html
With this fix we avoid to pass from homepage when we already are landed on "/building-class/" page.
And add a new entry for 'Building Classification Survey tool'  in 'share' page.
Tests are blocked by current broken platform <-> engine interface.
It is companion of gem/oq-platform-building-class/pull/10 PR.
CI is running here: https://ci.openquake.org/job/zdevel_oq-platform/412/
> add 'Building Classification Survey tool' and '?next=' to login form action

- verifier.sh
New oq-moon version with updated version of selenium and geckodriver
Test are green here: https://ci.openquake.org/job/zdevel_oq-platform/416/
> update version of geckodriver and selenium

- verifier.sh
So we should use the latest stable package available for now (engine 2.4)
https://ci.openquake.org/job/zdevel_oq-platform/435
> We do not provide nightly packages for precise anymore
